version: "3.7"

services:
  mempool_web:
    image: mempool/frontend:v2.4.0
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3006:3006
    command: "./wait-for mempool_mariadb:3306 --timeout=720 -- nginx -g 'daemon off;'"
    environment:
      FRONTEND_HTTP_PORT: "3006"
      BACKEND_MAINNET_HTTP_HOST: mempool_api

  mempool_api:
    image: mempool/backend:v2.4.1
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool_mariadb:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ${PWD}/data:/backend/cache
    environment:
      CORE_RPC_HOST: 192.168.1.105
      CORE_RPC_PORT: 18332
      CORE_RPC_USERNAME: bitcoiner
      CORE_RPC_PASSWORD: donttrustverify
      ELECTRUM_HOST: 192.168.1.105
      ELECTRUM_PORT: 50001
      ELECTRUM_TLS: "false"
      DATABASE_HOST: mempool_mariadb
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      MEMPOOL_HTTP_PORT: "8999"
      MEMPOOL_CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: "52560"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "info"

  mempool_mariadb:
    image: mariadb:10.5.12
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "moneyprintergobrrr"



