version: "3.7"

services:
  main:
    image: prettyrollcake/cln:v0.12.1@sha256:7fa7ec73351231931e8a58418f8aaa74b47890144b27a5ddb70c281d494c44a3
    restart: on-failure
    ports: 
      - 9735:9735 # p2p
    volumes:
      - "${PWD}/lightning:/data/.lightning"
    environment:
      LIGHTNINGD_NETWORK: testnet
    networks:
      bitcoin-net:
        ipv4_address: 172.40.10.10

networks:
  bitcoin-net:
    external: true

