version: "3.7"

services:
  electrm:
    image: getumbrel/electrs:v0.9.9@sha256:c2b9691f8a0b6f027cbcbc37a4c85ec6b28916bee4d0666ec30f75b034280f58
    restart: always
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: testnet
      ELECTRS_DAEMON_RPC_ADDR: 172.40.0.10:18332
      ELECTRS_DAEMON_P2P_ADDR: 172.40.0.10:18333
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50001"
      ELECTRS_DB_DIR: "/data/db"
    volumes:
      - "/home/pi4/bitcoin/data:/data/.bitcoin:ro"
      - "${PWD}/data/electrs:/data"
    ports:
      - "50001:50001"
    networks:
       my-network:
         ipv4_address: 172.40.20.10

networks:
  my-network:
    external: true

